// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_delete_name_index from "./routes/api/delete/[name]/index.ts";
import * as $api_upload_index from "./routes/api/upload/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FilelistElement from "./islands/FilelistElement.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/delete/[name]/index.ts": $api_delete_name_index,
    "./routes/api/upload/index.tsx": $api_upload_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/FilelistElement.tsx": $FilelistElement,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
