name: Build
on:
  push:
    branches: [main]
  release:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          make build
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: reproducible-bioinformatics/lemaitre:latest,reproducible-bioinformatics/lemaitre:${{ github.ref_name }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
